export const DRAWER_STATE = {
  SEARCH: "SEARCH",
  MAP: "MAP",
  ADD: "ADD",
  EDIT: "EDIT",
  CONFIRM: "CONFIRM"
};

export const ADDRESS_ERROR = {
  SERVICEABILITY_FAILED: "SERVICEABILITY_FAILED",
  NETWORK_ERROR: "NETWORK_ERROR",
  VALIDATION_ERROR: "VALIDATION_ERROR",
  ADDRESS_NOT_FOUND: "ADDRESS_NOT_FOUND",
  CACHE_MISS: "CACHE_MISS"
};
