/**
 * Submits the MSG91 verified access token to the backend for sign-in/sign-up.
 * @param {string} accessToken - Access token generated by the client-side MSG91 OTP widget.
 * @returns {Promise<any>} Response JSON containing JWT token and user details.
 */
export const msg91Login = async (accessToken) => {
  const url = `${window.API_BASE_URL}/api/auth/msg91-login`;
  console.log("MSG91 Login Request Url:", url);

  const res = await fetch(url, {
    method: "POST",
    headers: {
      "Content-Type": "application/json"
    },
    body: JSON.stringify({ accessToken })
  });

  const data = await res.json();
  if (!res.ok) {
    throw new Error(data.message || "Failed to log in via MSG91.");
  }
  return data;
};
